# Generated by Django 4.0 on 2023-07-31 23:44

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_rector', models.BooleanField(default=False)),
                ('is_registrar', models.BooleanField(default=False)),
                ('is_help_desk', models.BooleanField(default=False)),
                ('is_applicant', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='UserContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('Niger', 'Niger'), ('Cameroon', 'Cameroon'), ('Chad', 'Chad'), ('Kenya', 'Kenya')], max_length=20)),
                ('contact_address', models.CharField(blank=True, max_length=150, null=True)),
                ('home_address', models.CharField(blank=True, max_length=150, null=True)),
                ('state_origin', models.CharField(blank=True, max_length=36, null=True)),
                ('lga_origin', models.CharField(blank=True, max_length=36, null=True)),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('image', imagekit.models.fields.ProcessedImageField(default='avatar.jpg', upload_to='profile_images', validators=[accounts.models.FileExtensionValidator(['jpeg', 'jpg', 'gif', 'png'])])),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
        ),
    ]
