# Generated by Django 4.0 on 2023-07-27 08:36

import accounts.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=30, null=True)),
                ('last_name', models.CharField(blank=True, max_length=30, null=True)),
                ('date_birth', models.DateField(blank=True, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=11, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('country', models.CharField(choices=[('Nigeria', 'Nigeria'), ('Ghana', 'Ghana'), ('Niger', 'Niger'), ('Cameroon', 'Cameroon'), ('Chad', 'Chad'), ('Kenya', 'Kenya')], max_length=20)),
                ('contact_address', models.CharField(blank=True, max_length=150, null=True)),
                ('home_address', models.CharField(blank=True, max_length=150, null=True)),
                ('state_origin', models.CharField(blank=True, max_length=36, null=True)),
                ('lga_origin', models.CharField(blank=True, max_length=36, null=True)),
                ('image', imagekit.models.fields.ProcessedImageField(default='avatar.jpg', upload_to='profile_images', validators=[accounts.models.FileExtensionValidator(['jpeg', 'jpg', 'gif', 'png'])])),
                ('last_updated', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
